import "./globals.css";
import MobileNav from "./components/MobileNav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="de">
      <body className="bg-gray-50 min-h-screen text-gray-900 pb-16">
        {children}
        <MobileNav />
      </body>
    </html>
  );
}
