import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createClient } from '@supabase/supabase-js';
import { useState } from 'react';
import Link from "next/link";
import { useRouter } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
export const supabase = createClient(supabaseUrl, supabaseAnonKey);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function MobileNav() {
  'use client';
  const router = useRouter();
  async function handleLogout() {
    const { error } = await supabase.auth.signOut();
    router.push("/");
  }
  return (
    <nav className="fixed bottom-0 left-0 right-0 bg-white border-t flex justify-around items-center h-14 z-50 shadow md:hidden">
      <Link href="/swipe" className="flex flex-col items-center text-xs">
        <span>🔄</span>
        <span>Swipe</span>
      </Link>
      <Link href="/matches" className="flex flex-col items-center text-xs">
        <span>💬</span>
        <span>Matches</span>
      </Link>
      <Link href="/onboarding" className="flex flex-col items-center text-xs">
        <span>👤</span>
        <span>Profil</span>
      </Link>
      <button onClick={handleLogout} className="flex flex-col items-center text-xs text-red-500">
        <span>🚪</span>
        <span>Logout</span>
      </button>
    </nav>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="de">
      <body className="bg-gray-50 min-h-screen text-gray-900 pb-16">
        {children}
        <MobileNav />
      </body>
    </html>
  )
}
